const ROLES = Object.freeze({
  CREATOR: 'CREATOR',
  FREELANCER: 'FREELANCER',
  BRAND: 'BRAND',
  AGENCY: 'AGENCY',
  ADMIN: 'ADMIN',
});

const ROLE_VALUES = Object.values(ROLES);

const PUBLIC_SIGNUP_ROLES = [ROLES.CREATOR, ROLES.FREELANCER];

const OPPOSITE_FEED_ROLE = Object.freeze({
  [ROLES.CREATOR]: [ROLES.FREELANCER],
  [ROLES.FREELANCER]: [ROLES.CREATOR],
  [ROLES.BRAND]: [ROLES.CREATOR, ROLES.FREELANCER],
  [ROLES.AGENCY]: [ROLES.CREATOR, ROLES.FREELANCER],
});

module.exports = { ROLES, ROLE_VALUES, PUBLIC_SIGNUP_ROLES, OPPOSITE_FEED_ROLE };
