-- Distinguish block.service.js's auto-created moderation-trail report from
-- an explicit user-submitted report, so "did I report this?" and the
-- duplicate-report guard don't confuse the two.
ALTER TABLE "Report" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Backfill: any existing report whose reason matches the block-service
-- format was auto-generated, not explicitly submitted.
UPDATE "Report" SET "autoGenerated" = true WHERE "reason" LIKE 'Blocked by %';
